"""Provenance records.

SPEC.md 1.4 requires every project page to carry a provenance block: source name,
endpoint or file, query parameters, date pulled, record count, and known gaps. This
module is the single place those records are produced, so the block on the site and
the record in the repo cannot drift apart.

Records are written as JSON (machine-readable, consumed by the site) alongside
Markdown (human-readable, reviewed in the repo).
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROVENANCE_DIR = REPO_ROOT / "docs" / "provenance"

CHUNK = 1024 * 1024


def sha256_file(path: Path) -> str:
    """Checksum a file as published, without loading it into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass
class TableRecord:
    """One logical table, which may live inside an archive."""

    table: str
    archive: str | None
    member: str
    columns: list[str]
    record_count: int | None
    count_method: str
    notes: list[str] = field(default_factory=list)


@dataclass
class FileRecord:
    filename: str
    size_bytes: int
    sha256: str
    tables: list[TableRecord] = field(default_factory=list)


@dataclass
class ProvenanceRecord:
    """A single documented acquisition of source data."""

    source_name: str
    source_url: str
    access_method: str
    retrieved_at: str
    release_version: str | None
    files: list[FileRecord] = field(default_factory=list)
    known_gaps: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @staticmethod
    def now_utc() -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    @property
    def total_records(self) -> int:
        return sum(
            table.record_count or 0 for file in self.files for table in file.tables
        )

    def write(self, slug: str) -> tuple[Path, Path]:
        PROVENANCE_DIR.mkdir(parents=True, exist_ok=True)
        json_path = PROVENANCE_DIR / f"{slug}.json"
        md_path = PROVENANCE_DIR / f"{slug}.md"
        json_path.write_text(
            json.dumps(asdict(self), indent=2) + "\n", encoding="utf-8"
        )
        md_path.write_text(self.to_markdown(), encoding="utf-8")
        return json_path, md_path

    def to_markdown(self) -> str:
        lines = [
            "# Provenance record",
            "",
            "<!-- Generated by pipeline/provenance.py. Do not edit by hand. -->",
            "",
            f"- **Source:** {self.source_name}",
            f"- **Location:** {self.source_url}",
            f"- **Access method:** {self.access_method}",
            f"- **Retrieved:** {self.retrieved_at}",
            f"- **Release / version:** {self.release_version or 'NOT RECORDED'}",
            f"- **Total records:** {self.total_records:,}",
            "",
            "## Files",
            "",
        ]
        for file in self.files:
            size_mb = file.size_bytes / (1024 * 1024)
            lines += [
                f"### `{file.filename}`",
                "",
                f"- Size: {size_mb:,.1f} MiB ({file.size_bytes:,} bytes)",
                f"- SHA-256: `{file.sha256}`",
                "",
            ]
            for table in file.tables:
                count = (
                    f"{table.record_count:,}"
                    if table.record_count is not None
                    else "not counted"
                )
                lines += [
                    f"**Table `{table.table}`** (member `{table.member}`)",
                    "",
                    f"- Records: {count} (method: {table.count_method})",
                    f"- Columns ({len(table.columns)}): "
                    + ", ".join(f"`{c}`" for c in table.columns),
                    "",
                ]
                lines += [f"- Note: {n}" for n in table.notes]
                if table.notes:
                    lines.append("")

        if self.known_gaps:
            lines += ["## Known gaps", ""]
            lines += [f"- {gap}" for gap in self.known_gaps]
            lines.append("")
        if self.notes:
            lines += ["## Notes", ""]
            lines += [f"- {note}" for note in self.notes]
            lines.append("")
        return "\n".join(lines)
